### ISSUE TITLE
Improve Brightway Documentation

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/hackathons#10]
> "The documentation needs documentation."
> _a Bellevue Linux Users Group member, 2005_

## ⚠️ This issue is only for organizing tasks related to the hackathon setup. For actual issues related to documentation, compare the two relevant repositories:

https://github.com/brightway-lca/brightway-documentation-jupyter-book
https://github.com/brightway-lca/brightway-documentation-readthedocs

## ℹ️ Hackathon Information

As the functionality and the user base of Brightway continues to grow, the documentation must grow too. The current vision is to split up the documentation into:

1. A user-friendly, interactive documentation based on [Jupyter Books](https://jupyterbook.org/en/stable/intro.html). This includes a comprehensive "getting started" page and has the ability to run small snippets of Brightway code in-browser.
2. A developer-focused detailed API documentation based on [Sphinx](https://www.sphinx-doc.org/en/master/) and hosted at [readthedocs.com](https://readthedocs.org/). This takes in-code documentation, such as function [docstrings](https://www.geeksforgeeks.org/python-docstrings/) to generate a detailed outline.

## 🗓 Hackathon Schedule

 - [x] "what does the perfect documentation look like?"

#### BEFORE the Hackathon

 - [x] create readthedocs.org account
 - [x] give multiple users (Brightway developers) access to readthedocs.org site

#### DURING the Hackathon

 - [x] create [single documentation for multiple packages](http://fmarco76.github.io/git%20and%20related%20services/readthedocs) (bw_agg, bw_calc, etc.)
 - [x] move existing Sphinx documetation from `https://2.docs.brightway.dev/technical/*` to `brightway.readthedocs.org`
 - [x] create issues in the respective repos if documentation is missing

#### BEFORE the Hackathon

 - [ ] move remaining pages to existing Jupyter Book
 - [x] create setup ("getting started with Jupyter Books") documentation for hackathon participants

#### DURING the Hackathon

 - [ ] create outline of documentation
 - [ ] set up in-browser code execution (`binder.org` or `colabs` or `hub.brightway.dev`)

## 🌐 Useful Links
[Brightway Strategic Development Plan](https://github.com/brightway-lca/enhancement-proposals/blob/main/Brightway%20strategic%20development%20plan.md)
[Brightway Jupyter Books Documentation](https://github.com/brightway-lca/jupyter-book-brightway-documentation)
[Diataxis Documentation Framework](https://diataxis.fr/)
[documentation-as-a-way-to-build-community](https://labs.quansight.org/blog/2020/03/documentation-as-a-way-to-build-community)
[Gallery of Jupyter Books](https://executablebooks.org/en/latest/gallery.html)

**Comment by michaelweinold** [comment]
Compare:

https://github.com/brightway-lca/jupyter-book-brightway-documentation/issues/1

**Comment by shirubana** [comment]
Not sure if useful, but I really like the template that [pvlib implemented](https://pvlib-python.readthedocs.io/en/stable/) and this [pull request](https://github.com/NREL/bifacial_radiance/commit/cd61ac2fad26cc0647edb48b7bf6bd09fcf6ff24) shows the changes in my repo which looked similar to brightways to obtain that sidebar and topbar division of content, as well as the Gallery of journal examples.

**Comment by michaelweinold** [comment]
> Not sure if useful, but I really like the template that [pvlib implemented](https://pvlib-python.readthedocs.io/en/stable/) and this [pull request](https://github.com/NREL/bifacial_radiance/commit/cd61ac2fad26cc0647edb48b7bf6bd09fcf6ff24) shows the changes in my repo which looked similar to brightways to obtain that sidebar and topbar division of content, as well as the Gallery of journal examples.

This readthedocs page looks great - we'll make sure to adapt our prototoype to reflect the layout.

**Comment by shirubana** [comment]
Also as an afterthought -- I don't see this in an obvious manner in the current documentation, so it'd be great to include a What's new with every sub package release that feeds into the main whats new.

**Comment by michaelweinold** [comment]
> Also as an afterthought -- I don't see this in an obvious manner in the current documentation, so it'd be great to include a What's new with every sub package release that feeds into the main whats new.

Agreed! There will be more structured changelog template also. Compare also the https://gitter.im/brightway-lca/announcements Gitter room for announcements of this nature.

**Comment by michaelweinold** [comment]
Brainstorming session _"what would the worst documentation look like"_?
<img width="1040" alt="Screenshot 2022-10-03 at 16 15 20" src="https://user-images.githubusercontent.com/23102087/193599954-a8776654-3fc9-471d-8e99-676993d46083.png">

**Comment by michaelweinold** [comment]
All further tasks are tracked in the `documentation` and the `training` repos:
https://github.com/brightway-lca/brightway-documentation/issues
https://github.com/brightway-lca/brightway-training/issues

**Comment by michaelweinold** [comment]
Brainstorming session result:

[Documentation Hackathon the worst possible documentation.pdf](https://github.com/brightway-lca/hackathons/files/9738767/Documentation.Hackathon.the.worst.possible.documentation.pdf)
