### ISSUE TITLE
Obtain ILCD datasets from REST end point or file system

### ISSUE THREAD

**Issue by okworx** [brightway-lca/hackathons#15]
ILCD datasets can either reside on a remote node somewhere on the internet where we'll need to fetch it from or be provided as a ZIP archive on the local filesystem.

## From the file system

- [ ] take an ILCD ZIP archive from the file system and extract the ZIP to a temporary location

## From a REST service (soda4LCA node)

(Authentication is not necessary for now as we've got plenty of nodes that don't require any authentication to access the data.)

We want to:
- [ ] browse/search for datasets on a node with a given base URL in a given data stock
- [ ] fetch a specific dataset including dependencies as ZIP file
- [ ] extract the ZIP to a temporary location

**Comment by cmutel** [comment]
Issue closed during cleanup for Brightcon 2023
