### ISSUE TITLE
create internal map of flow properties from reference table

### ISSUE THREAD

**Issue by okworx** [brightway-lca/hackathons#17]
In the attached spreadsheet, we have all flow properties with their UUID and reference unit in the sheet "FlowProperties".

We need those in a map where we can simply look them up by their UUID.

[EF-FPs_UGs.xlsx](https://github.com/brightway-lca/hackathons/files/9674869/EF-FPs_UGs.xlsx)

**Comment by cmutel** [comment]
Issue closed during cleanup for Brightcon 2023
