### ISSUE TITLE
Improve Brightway documentation

### ISSUE THREAD

**Issue by cmutel** [brightway-lca/hackathons#26]
There is a lot that could be done to improve the Brightway documentation: https://github.com/brightway-lca/brightway-documentation

No specific list of tasks, but this is an excellent place for people who aren't yet comfortable contributing code.

**Comment by cmutel** [comment]
Nominating @michaelweinold for coordinator :)

**Comment by michaelweinold** [comment]
Documentation? What documentation 🧐 Never heard of any documentation 🙈
